"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24 17:55:48.720577
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idp_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("idp_subject"),
    )
    op.create_table(
        "organization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("org_number", sa.String(length=20), nullable=True),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("encrypted_dek", sa.Text(), nullable=True),
        sa.Column("ai_monthly_token_budget", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_trace",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("task", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=50), nullable=True),
        sa.Column("input_hash", sa.String(length=32), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("rejected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("downgraded", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("package", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_trace_org_id"), "ai_trace", ["org_id"], unique=False)
    op.create_table(
        "ai_usage",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("tokens", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "month"),
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("user_email", sa.String(length=320), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_event_action"), "audit_event", ["action"], unique=False)
    op.create_index(op.f("ix_audit_event_org_id"), "audit_event", ["org_id"], unique=False)
    op.create_table(
        "company",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("org_number", sa.String(length=20), nullable=True),
        sa.Column("legal_form", sa.String(length=10), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("vat_period", sa.String(length=10), nullable=False),
        sa.Column("food_retail", sa.Boolean(), nullable=False),
        sa.Column("materiality", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("has_overdraft", sa.Boolean(), nullable=False),
        sa.Column("accounting_method_override", sa.String(length=10), nullable=True),
        sa.Column("source_system", sa.String(length=30), nullable=True),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "org_number"),
    )
    op.create_index(op.f("ix_company_org_id"), "company", ["org_id"], unique=False)
    op.create_table(
        "organization_membership",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("can_payroll", sa.Boolean(), nullable=False),
        sa.Column("can_aml", sa.Boolean(), nullable=False),
        sa.Column("can_approve_reports", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id"),
    )
    op.create_index(op.f("ix_organization_membership_org_id"), "organization_membership", ["org_id"], unique=False)
    op.create_table(
        "rule_proposal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("proposals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reviewed_by", sa.String(length=320), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rule_proposal_org_id"), "rule_proposal", ["org_id"], unique=False)
    op.create_table(
        "account",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("type", sa.String(length=1), nullable=True),
        sa.Column("sru", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("company_id", "number"),
    )
    op.create_index(op.f("ix_account_org_id"), "account", ["org_id"], unique=False)
    op.create_table(
        "aml_assessment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.String(length=320), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_aml_assessment_company_id"), "aml_assessment", ["company_id"], unique=False)
    op.create_index(op.f("ix_aml_assessment_org_id"), "aml_assessment", ["org_id"], unique=False)
    op.create_table(
        "case_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("case_key", sa.String(length=40), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=False),
        sa.Column("suggested_action", sa.Text(), nullable=False),
        sa.Column("ask_client_suggested", sa.Boolean(), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("memory_hint", sa.Text(), nullable=True),
        sa.Column("ai", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "case_key"),
    )
    op.create_index(op.f("ix_case_record_company_id"), "case_record", ["company_id"], unique=False)
    op.create_index(op.f("ix_case_record_org_id"), "case_record", ["org_id"], unique=False)
    op.create_table(
        "client_question",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("case_key", sa.String(length=40), nullable=True),
        sa.Column("finding_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("recipient_email", sa.String(length=320), nullable=True),
        sa.Column(
            "display", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("sent_by", sa.String(length=320), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reminder_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_client_question_company_id"), "client_question", ["company_id"], unique=False)
    op.create_index(op.f("ix_client_question_org_id"), "client_question", ["org_id"], unique=False)
    op.create_table(
        "company_assignment",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("company_id", "user_id"),
    )
    op.create_index(op.f("ix_company_assignment_org_id"), "company_assignment", ["org_id"], unique=False)
    op.create_table(
        "connection",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tenant_ref", sa.String(length=100), nullable=True),
        sa.Column("secret_ref", sa.Text(), nullable=True),
        sa.Column("authorized_by", sa.UUID(), nullable=True),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("cost_model", sa.String(length=30), nullable=True),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connection_company_id"), "connection", ["company_id"], unique=False)
    op.create_index(op.f("ix_connection_org_id"), "connection", ["org_id"], unique=False)
    op.create_table(
        "counterparty_alias",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("confirmed_by", sa.String(length=320), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "company_id", "key"),
    )
    op.create_index(op.f("ix_counterparty_alias_org_id"), "counterparty_alias", ["org_id"], unique=False)
    op.create_table(
        "finding",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("rule_code", sa.String(length=60), nullable=False),
        sa.Column("rule_version", sa.String(length=10), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=True),
        sa.Column("legal_basis", sa.Text(), nullable=True),
        sa.Column("vouchers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("accounts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seen_in_reviews", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.String(length=320), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suppression_id", sa.String(length=40), nullable=True),
        sa.Column("memory_suggestion", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("case_key", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "fingerprint"),
    )
    op.create_index(op.f("ix_finding_case_key"), "finding", ["case_key"], unique=False)
    op.create_index(op.f("ix_finding_company_id"), "finding", ["company_id"], unique=False)
    op.create_index(op.f("ix_finding_org_id"), "finding", ["org_id"], unique=False)
    op.create_index(op.f("ix_finding_rule_code"), "finding", ["rule_code"], unique=False)
    op.create_index(op.f("ix_finding_status"), "finding", ["status"], unique=False)
    op.create_table(
        "fiscal_year",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "start_date"),
    )
    op.create_index(op.f("ix_fiscal_year_company_id"), "fiscal_year", ["company_id"], unique=False)
    op.create_index(op.f("ix_fiscal_year_org_id"), "fiscal_year", ["org_id"], unique=False)
    op.create_table(
        "mapping_override",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("account", sa.Integer(), nullable=False),
        sa.Column("target", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "company_id", "kind", "account"),
    )
    op.create_index(op.f("ix_mapping_override_org_id"), "mapping_override", ["org_id"], unique=False)
    op.create_table(
        "period_review",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("maturity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_by", sa.String(length=320), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("commentary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("client_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "period"),
    )
    op.create_index(op.f("ix_period_review_company_id"), "period_review", ["company_id"], unique=False)
    op.create_index(op.f("ix_period_review_org_id"), "period_review", ["org_id"], unique=False)
    op.create_table(
        "resolution",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("signature_exact", sa.String(length=40), nullable=False),
        sa.Column("signature_loose", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("rule_code", sa.String(length=60), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("decided_by", sa.String(length=320), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("times_reused", sa.Integer(), nullable=False),
        sa.Column("example_finding_id", sa.String(length=40), nullable=True),
        sa.Column("example_title", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resolution_company_id"), "resolution", ["company_id"], unique=False)
    op.create_index(op.f("ix_resolution_org_id"), "resolution", ["org_id"], unique=False)
    op.create_index(op.f("ix_resolution_signature_exact"), "resolution", ["signature_exact"], unique=False)
    op.create_index(op.f("ix_resolution_signature_loose"), "resolution", ["signature_loose"], unique=False)
    op.create_table(
        "rule_param_override",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("rule_code", sa.String(length=60), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "company_id", "rule_code"),
    )
    op.create_index(op.f("ix_rule_param_override_org_id"), "rule_param_override", ["org_id"], unique=False)
    op.create_table(
        "source_file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("detected_format", sa.String(length=20), nullable=True),
        sa.Column("encoding", sa.String(length=20), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "parse_issues",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("delete_after", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_file_company_id"), "source_file", ["company_id"], unique=False)
    op.create_index(op.f("ix_source_file_org_id"), "source_file", ["org_id"], unique=False)
    op.create_index(op.f("ix_source_file_sha256"), "source_file", ["sha256"], unique=False)
    op.create_table(
        "suppression_rule",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("rule_code", sa.String(length=60), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=320), nullable=False),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("accounts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("text_contains", sa.Text(), nullable=True),
        sa.Column("max_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppression_rule_org_id"), "suppression_rule", ["org_id"], unique=False)
    op.create_table(
        "tax_account_import",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("transactions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("imported_by", sa.String(length=320), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tax_account_import_company_id"), "tax_account_import", ["company_id"], unique=False)
    op.create_index(op.f("ix_tax_account_import_org_id"), "tax_account_import", ["org_id"], unique=False)
    op.create_table(
        "import_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_year_id", sa.UUID(), nullable=False),
        sa.Column("source_file_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("parser_version", sa.String(length=20), nullable=True),
        sa.Column("has_vouchers", sa.Boolean(), nullable=False),
        sa.Column(
            "stats", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["fiscal_year_id"],
            ["fiscal_year.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "seq"),
    )
    op.create_index(op.f("ix_import_run_company_id"), "import_run", ["company_id"], unique=False)
    op.create_index(op.f("ix_import_run_org_id"), "import_run", ["org_id"], unique=False)
    op.create_table(
        "voucher_version",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_year_id", sa.UUID(), nullable=False),
        sa.Column("series", sa.String(length=20), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("reg_date", sa.Date(), nullable=True),
        sa.Column("signature", sa.String(length=100), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("valid_from", sa.Integer(), nullable=False),
        sa.Column("valid_to", sa.Integer(), nullable=True),
        sa.Column("source_line", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["fiscal_year_id"],
            ["fiscal_year.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_voucher_current",
        "voucher_version",
        ["company_id", "fiscal_year_id", "series", "number"],
        unique=False,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_index("ix_voucher_date", "voucher_version", ["company_id", "date"], unique=False)
    op.create_index(op.f("ix_voucher_version_company_id"), "voucher_version", ["company_id"], unique=False)
    op.create_index(op.f("ix_voucher_version_org_id"), "voucher_version", ["org_id"], unique=False)
    op.create_table(
        "account_period_balance",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("account", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["import_id"], ["import_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_id", "period", "account"),
    )
    op.create_index(
        op.f("ix_account_period_balance_company_id"), "account_period_balance", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_account_period_balance_org_id"), "account_period_balance", ["org_id"], unique=False)
    op.create_table(
        "period_amount",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("account", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["import_id"], ["import_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_id", "kind", "period", "account"),
    )
    op.create_index(op.f("ix_period_amount_company_id"), "period_amount", ["company_id"], unique=False)
    op.create_index(op.f("ix_period_amount_org_id"), "period_amount", ["org_id"], unique=False)
    op.create_table(
        "pipeline_step",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("step", sa.String(length=50), nullable=False),
        sa.Column("step_version", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["import_id"], ["import_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_id", "step", "step_version"),
    )
    op.create_index(op.f("ix_pipeline_step_org_id"), "pipeline_step", ["org_id"], unique=False)
    op.create_table(
        "transaction_row",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("voucher_version_id", sa.BigInteger(), nullable=False),
        sa.Column("row_no", sa.Integer(), nullable=False),
        sa.Column("account", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("trans_date", sa.Date(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "objects", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("source_line", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["voucher_version_id"], ["voucher_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_row_account", "transaction_row", ["company_id", "account"], unique=False)
    op.create_index(op.f("ix_transaction_row_company_id"), "transaction_row", ["company_id"], unique=False)
    op.create_index(op.f("ix_transaction_row_org_id"), "transaction_row", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_transaction_row_voucher_version_id"), "transaction_row", ["voucher_version_id"], unique=False
    )
    op.create_table(
        "year_balance",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=5), nullable=False),
        sa.Column("account", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["import_id"], ["import_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_id", "kind", "account"),
    )
    op.create_index(op.f("ix_year_balance_company_id"), "year_balance", ["company_id"], unique=False)
    op.create_index(op.f("ix_year_balance_org_id"), "year_balance", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_year_balance_org_id"), table_name="year_balance")
    op.drop_index(op.f("ix_year_balance_company_id"), table_name="year_balance")
    op.drop_table("year_balance")
    op.drop_index(op.f("ix_transaction_row_voucher_version_id"), table_name="transaction_row")
    op.drop_index(op.f("ix_transaction_row_org_id"), table_name="transaction_row")
    op.drop_index(op.f("ix_transaction_row_company_id"), table_name="transaction_row")
    op.drop_index("ix_row_account", table_name="transaction_row")
    op.drop_table("transaction_row")
    op.drop_index(op.f("ix_pipeline_step_org_id"), table_name="pipeline_step")
    op.drop_table("pipeline_step")
    op.drop_index(op.f("ix_period_amount_org_id"), table_name="period_amount")
    op.drop_index(op.f("ix_period_amount_company_id"), table_name="period_amount")
    op.drop_table("period_amount")
    op.drop_index(op.f("ix_account_period_balance_org_id"), table_name="account_period_balance")
    op.drop_index(op.f("ix_account_period_balance_company_id"), table_name="account_period_balance")
    op.drop_table("account_period_balance")
    op.drop_index(op.f("ix_voucher_version_org_id"), table_name="voucher_version")
    op.drop_index(op.f("ix_voucher_version_company_id"), table_name="voucher_version")
    op.drop_index("ix_voucher_date", table_name="voucher_version")
    op.drop_index("ix_voucher_current", table_name="voucher_version", postgresql_where=sa.text("valid_to IS NULL"))
    op.drop_table("voucher_version")
    op.drop_index(op.f("ix_import_run_org_id"), table_name="import_run")
    op.drop_index(op.f("ix_import_run_company_id"), table_name="import_run")
    op.drop_table("import_run")
    op.drop_index(op.f("ix_tax_account_import_org_id"), table_name="tax_account_import")
    op.drop_index(op.f("ix_tax_account_import_company_id"), table_name="tax_account_import")
    op.drop_table("tax_account_import")
    op.drop_index(op.f("ix_suppression_rule_org_id"), table_name="suppression_rule")
    op.drop_table("suppression_rule")
    op.drop_index(op.f("ix_source_file_sha256"), table_name="source_file")
    op.drop_index(op.f("ix_source_file_org_id"), table_name="source_file")
    op.drop_index(op.f("ix_source_file_company_id"), table_name="source_file")
    op.drop_table("source_file")
    op.drop_index(op.f("ix_rule_param_override_org_id"), table_name="rule_param_override")
    op.drop_table("rule_param_override")
    op.drop_index(op.f("ix_resolution_signature_loose"), table_name="resolution")
    op.drop_index(op.f("ix_resolution_signature_exact"), table_name="resolution")
    op.drop_index(op.f("ix_resolution_org_id"), table_name="resolution")
    op.drop_index(op.f("ix_resolution_company_id"), table_name="resolution")
    op.drop_table("resolution")
    op.drop_index(op.f("ix_period_review_org_id"), table_name="period_review")
    op.drop_index(op.f("ix_period_review_company_id"), table_name="period_review")
    op.drop_table("period_review")
    op.drop_index(op.f("ix_mapping_override_org_id"), table_name="mapping_override")
    op.drop_table("mapping_override")
    op.drop_index(op.f("ix_fiscal_year_org_id"), table_name="fiscal_year")
    op.drop_index(op.f("ix_fiscal_year_company_id"), table_name="fiscal_year")
    op.drop_table("fiscal_year")
    op.drop_index(op.f("ix_finding_status"), table_name="finding")
    op.drop_index(op.f("ix_finding_rule_code"), table_name="finding")
    op.drop_index(op.f("ix_finding_org_id"), table_name="finding")
    op.drop_index(op.f("ix_finding_company_id"), table_name="finding")
    op.drop_index(op.f("ix_finding_case_key"), table_name="finding")
    op.drop_table("finding")
    op.drop_index(op.f("ix_counterparty_alias_org_id"), table_name="counterparty_alias")
    op.drop_table("counterparty_alias")
    op.drop_index(op.f("ix_connection_org_id"), table_name="connection")
    op.drop_index(op.f("ix_connection_company_id"), table_name="connection")
    op.drop_table("connection")
    op.drop_index(op.f("ix_company_assignment_org_id"), table_name="company_assignment")
    op.drop_table("company_assignment")
    op.drop_index(op.f("ix_client_question_org_id"), table_name="client_question")
    op.drop_index(op.f("ix_client_question_company_id"), table_name="client_question")
    op.drop_table("client_question")
    op.drop_index(op.f("ix_case_record_org_id"), table_name="case_record")
    op.drop_index(op.f("ix_case_record_company_id"), table_name="case_record")
    op.drop_table("case_record")
    op.drop_index(op.f("ix_aml_assessment_org_id"), table_name="aml_assessment")
    op.drop_index(op.f("ix_aml_assessment_company_id"), table_name="aml_assessment")
    op.drop_table("aml_assessment")
    op.drop_index(op.f("ix_account_org_id"), table_name="account")
    op.drop_table("account")
    op.drop_index(op.f("ix_rule_proposal_org_id"), table_name="rule_proposal")
    op.drop_table("rule_proposal")
    op.drop_index(op.f("ix_organization_membership_org_id"), table_name="organization_membership")
    op.drop_table("organization_membership")
    op.drop_index(op.f("ix_company_org_id"), table_name="company")
    op.drop_table("company")
    op.drop_index(op.f("ix_audit_event_org_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_action"), table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_table("ai_usage")
    op.drop_index(op.f("ix_ai_trace_org_id"), table_name="ai_trace")
    op.drop_table("ai_trace")
    op.drop_table("organization")
    op.drop_table("app_user")
    # ### end Alembic commands ###
